### ISSUE TITLE
Scanner interrupt error

### ISSUE THREAD

**Issue by wo4zhuzi** [ontio/ontology#1282]
Cannot continue when running to 1293991 blocks

error message:

```
[ ERROR] [2020-09-28 10:39:20] com.github.ontio.thread.TxnHandlerThread [172] - handleOneTxn RestfulException...{}
com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}
        at com.github.ontio.network.rest.RestClient.getContractJson(RestClient.java:191)
        at com.github.ontio.sdk.manager.ConnectMgr.getContractJson(ConnectMgr.java:235)
        at com.github.ontio.thread.TxnHandlerThread.getSmartContractInfo(TxnHandlerThread.java:746)
        at com.github.ontio.thread.TxnHandlerThread.handleOneTxn(TxnHandlerThread.java:99)
        at com.github.ontio.thread.TxnHandlerThread.asyncHandleTxn(TxnHandlerThread.java:71)
        at com.github.ontio.thread.TxnHandlerThread$$FastClassBySpringCGLIB$$67ea581d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}
        at com.github.ontio.network.rest.RestClient.getContractJson(RestClient.java:191)
        at com.github.ontio.sdk.manager.ConnectMgr.getContractJson(ConnectMgr.java:235)
        at com.github.ontio.thread.TxnHandlerThread.getSmartContractInfo(TxnHandlerThread.java:746)
        at com.github.ontio.thread.TxnHandlerThread.handleOneTxn(TxnHandlerThread.java:99)
        at com.github.ontio.thread.TxnHandlerThread.asyncHandleTxn(TxnHandlerThread.java:71)
        at com.github.ontio.thread.TxnHandlerThread$$FastClassBySpringCGLIB$$67ea581d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
[ ERROR] [2020-09-28 10:39:20] com.github.ontio.asyncService.BlockHandleService [98] - error...session.rollback
java.util.concurrent.ExecutionException: com.github.ontio.network.exception.RestfulException: {"Action":"getcontract","Desc":"INTERNAL ERROR","Error":45001,"Result":"","Version":"1.0.0"}
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
```

**Comment by lucas7788** [comment]
@wo4zhuzi   Are you invoking getContractJson method?  what is your contractAddress?  do you have deploy the contract?

**Comment by wo4zhuzi** [comment]
I ran "ontology explorer"

**Comment by lucas7788** [comment]
@wo4zhuzi  Can you describe in detail what you did？ Where did you see this command?
