### ISSUE TITLE
[ERROR] GID 1, Incorrectly book keepers key panic: division by zero

### ISSUE THREAD

**Issue by jxzsxsp** [ontio/ontology#22]
[root@yueyue ontology]# ./ontology 
2018/04/02 17:22:36.895985 [TRACE] GID 1, main() main.go:76 Node version:  8728
2018/04/02 17:22:36.896051 [WARN ] GID 1, Config error:  unknown signature scheme , use SHA256withECDSA as default
2018/04/02 17:22:36.896080 [INFO ] GID 1, 0. Open the account
Password:
2018/04/02 17:23:04.817205 [INFO ] GID 1, 1. Loading the Ledger
2018/04/02 17:23:04.837925 [INFO ] GID 1, InitCurrentBlock currentBlockHash b4d15d165db9f7a06e014c4fab6b5f8e2c9e1f02e04000b736b79e3843268e2c currentBlockHeight 0
2018/04/02 17:23:04.838455 [ERROR] GID 1, Incorrectly book keepers key
panic: division by zero

goroutine 1 [running]:
math/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420026300, 0x1, 0x5, 0x0, ...)
	/usr/local/go/src/math/big/nat.go:571 +0x450
math/big.(*Int).QuoRem(0xc4201be820, 0xc42000cbe0, 0xc4201be840, 0xc4212713f0, 0x0, 0xc4201be840)
	/usr/local/go/src/math/big/int.go:232 +0xbf
math/big.(*Int).Div(0xc4201be820, 0xc42000cbe0, 0xc4201be840, 0x30)
	/usr/local/go/src/math/big/int.go:243 +0x6a
github.com/ontio/ontology/smartcontract/service/native.OntInit(0xc4201bcd20, 0xc420069280, 0xc4205deb30)
	/data/gopath/src/github.com/ontio/ontology/smartcontract/service/native/ont.go:55 +0x1c2
github.com/ontio/ontology/smartcontract/service/native.(*NativeService).Invoke(0xc4201bcd20, 0xc4201be7a0, 0xca781c61f7a3a83a)
	/data/gopath/src/github.com/ontio/ontology/smartcontract/service/native/native_state.go:94 +0x23d
github.com/ontio/ontology/smartcontract.(*SmartContract).Execute(0xc420086f00, 0x0, 0x0)
	/data/gopath/src/github.com/ontio/ontology/smartcontract/smartcontract.go:100 +0x1b3
github.com/ontio/ontology/core/store/ledgerstore.(*StateStore).HandleInvokeTransaction(0xc420068280, 0xac36c0, 0xc4200ac300, 0xc4201be700, 0xc42009ad20, 0xc4201b9aa0, 0xabf1a0, 0xc4201be100, 0xc4201be700, 0x20)
	/data/gopath/src/github.com/ontio/ontology/core/store/ledgerstore/tx_handler.go:105 +0x30a
github.com/ontio/ontology/core/store/ledgerstore.(*LedgerStoreImp).handleTransaction(0xc4200ac300, 0xc4201be700, 0xc4201b9aa0, 0xc42009ad20, 0x0, 0x0)
	/data/gopath/src/github.com/ontio/ontology/core/store/ledgerstore/ledger_store.go:745 +0x105
github.com/ontio/ontology/core/store/ledgerstore.(*LedgerStoreImp).saveBlockToStateStore(0xc4200ac300, 0xc4201b9aa0, 0x0, 0x0)
	/data/gopath/src/github.com/ontio/ontology/core/store/ledgerstore/ledger_store.go:629 +0x1d7
github.com/ontio/ontology/core/store/ledgerstore.(*LedgerStoreImp).saveBlock(0xc4200ac300, 0xc4201b9aa0, 0x0, 0x0)
	/data/gopath/src/github.com/ontio/ontology/core/store/ledgerstore/ledger_store.go:714 +0x268
github.com/ontio/ontology/core/store/ledgerstore.(*LedgerStoreImp).InitLedgerStoreWithGenesisBlock(0xc4200ac300, 0xc4201b9aa0, 0xc42001f5d0, 0x1, 0x1, 0x0, 0x53084b)
	/data/gopath/src/github.com/ontio/ontology/core/store/ledgerstore/ledger_store.go:140 +0x620
github.com/ontio/ontology/core/ledger.(*Ledger).Init(0xc42018c2e0, 0xc42001f5d0, 0x1, 0x1, 0x1, 0x1)
	/data/gopath/src/github.com/ontio/ontology/core/ledger/ledger.go:60 +0x10f
main.main()
	/data/gopath/src/github.com/ontio/ontology/main.go:115 +0x51c
[root@yueyue ontology]#

**Comment by laizy** [comment]
the Bookkeepers may not correctly set in the config.json file.

**Comment by panther142** [comment]
See my closed PR #20 and the fix #23 to resolve this
